project:
  type: website
  resources: pgp.txt
website:
  title: "Jonas Neubert"
  description: "Jonas Neubert - Personal Website"
  favicon: favicon.png
  site-url: https://neubert.eu
  page-footer: Proudly created with [Quarto](https://quarto.org).
format:
  html:
    theme: solar
    css: styles.css
    linkcolor: "#839496"
    email-obfuscation: javascript
execute:
  freeze: auto
  