project:
  type: website
  resources: pgp.txt
website:
  description: "Jonas Neubert's personal website."
  favicon: favicon.png
  site-url: https://neubert.eu
  page-footer: Proudly created with [Quarto](https://quarto.org) v<?quarto.version?>.
format:
  html:
    theme: solar
    css: styles.css
    linkcolor: "#839496"
    email-obfuscation: javascript
execute:
  freeze: auto
filters:
  - quarto-version.lua
