---
title: "Go Workshop at UCM"
author: "Jonas Neubert"
date: "2023-06-16"
date-format: long
format:
  html: default
  # NB: PDF cannot be rendered by GitHub Pages, so needs to be rendered and uploaded manually to be updated
---

::: {.callout-note title="Workshop Description" collapse="true" appearance="simple"}
Go is more than just a game. It is a journey of discovery, a way of living, and a source of wisdom. Go is one of the oldest and most sophisticated board games in the world, with a rich history of over 4,000 years. It has been played by thinkers, leaders, artists, and innovators across time and space. Go challenges you to create territory, capture stones, and balance attack and defense on a 19x19 grid. But it also teaches you essential skills such as patience, discipline, open-mindedness, creativity, and intuition. In this workshop, you will learn the basics of Go while exploring the philosophy behind Go. You will see how Go can be a metaphor for life, where each move is a decision that affects your future. You will also experience how Go can be a dialogue of hands, where you communicate with your opponent through your stones. Whether you are new to Go or already familiar with it, this workshop will inspire you to Go with the flow and find joy in playing this ancient board game.
:::

Thanks for joining the workshop at [UCM's 20th Anniversary Knowledge Festival](https://www.maastrichtuniversity.nl/ucm-anniversary-workshops). Below, I have collected a few useful resources to get you started if you wish to explore this fascinating game afterwards. You may also download this overview as [PDF file](/go_workshop_UCM.pdf).

If you have any feedback or questions, you are more than welcome to send me an email to [jonas@neubert.eu](mailto:jonas@neubert.eu)

## Reading Materials

- [A Go Guide by a Beginner (free book, beginner friendly)](https://www.gobook.eu)
- [Sensei's Library (a wiki dedicated to Go)](https://senseis.xmp.net)

## Playing Go Online (against AI or other players)

- [Online Go Server (OGS)](https://online-go.com)
- You can find my profile [here](https://online-go.com/user/view/1325965), please feel free to send me a challenge any time

## Go Exercises

- [For Beginners](https://online-go.com/learn-to-play-go/)
- [Intermediate to Advanced (only partially free)](https://gomagic.org/go-problems/)
- For more, just search for *Go Tsumego*

## Youtube

- [Go Magic (beginner friendly)](https://www.youtube.com/@GoMagic)
  - [Go Rules & Basics](https://www.youtube.com/playlist?list=PL4DLlaT_bvDG5y6WSfXU8cQsTsb4o3YnT)
- [Go Review - A video 4,000 years in the making](https://www.youtube.com/watch?v=RRBjN8empIs)
- [Nick Sibicky (intermediate lectures)](https://www.youtube.com/@NickSibicky)


## Movies / Documentaries

- [AlphaGo (full movie)](https://www.youtube.com/watch?v=WXuK6gekU1Y)
- [The Surrounding Game (trailer)](https://www.youtube.com/watch?v=QyfWChDhtu0)
